# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import file_serve_pb2 as file__serve__pb2


class FileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFile = channel.unary_stream(
                '/fileserve.FileService/GetFile',
                request_serializer=file__serve__pb2.FileRequest.SerializeToString,
                response_deserializer=file__serve__pb2.FileResponse.FromString,
                )
        self.GetFileList = channel.unary_stream(
                '/fileserve.FileService/GetFileList',
                request_serializer=file__serve__pb2.FileListRequest.SerializeToString,
                response_deserializer=file__serve__pb2.FileNameResponse.FromString,
                )


class FileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFile': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=file__serve__pb2.FileRequest.FromString,
                    response_serializer=file__serve__pb2.FileResponse.SerializeToString,
            ),
            'GetFileList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFileList,
                    request_deserializer=file__serve__pb2.FileListRequest.FromString,
                    response_serializer=file__serve__pb2.FileNameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fileserve.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/fileserve.FileService/GetFile',
            file__serve__pb2.FileRequest.SerializeToString,
            file__serve__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFileList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/fileserve.FileService/GetFileList',
            file__serve__pb2.FileListRequest.SerializeToString,
            file__serve__pb2.FileNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
