# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_serve.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='file_serve.proto',
  package='fileserve',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x66ile_serve.proto\x12\tfileserve\"\x1b\n\x0b\x46ileRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x11\n\x0f\x46ileListRequest\"\x1c\n\x0c\x46ileResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\" \n\x10\x46ileNameResponse\x12\x0c\n\x04name\x18\x01 \x01(\t2\x99\x01\n\x0b\x46ileService\x12>\n\x07GetFile\x12\x16.fileserve.FileRequest\x1a\x17.fileserve.FileResponse\"\x00\x30\x01\x12J\n\x0bGetFileList\x12\x1a.fileserve.FileListRequest\x1a\x1b.fileserve.FileNameResponse\"\x00\x30\x01\x62\x06proto3'
)




_FILEREQUEST = _descriptor.Descriptor(
  name='FileRequest',
  full_name='fileserve.FileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='fileserve.FileRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=58,
)


_FILELISTREQUEST = _descriptor.Descriptor(
  name='FileListRequest',
  full_name='fileserve.FileListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=77,
)


_FILERESPONSE = _descriptor.Descriptor(
  name='FileResponse',
  full_name='fileserve.FileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='fileserve.FileResponse.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=107,
)


_FILENAMERESPONSE = _descriptor.Descriptor(
  name='FileNameResponse',
  full_name='fileserve.FileNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='fileserve.FileNameResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['FileRequest'] = _FILEREQUEST
DESCRIPTOR.message_types_by_name['FileListRequest'] = _FILELISTREQUEST
DESCRIPTOR.message_types_by_name['FileResponse'] = _FILERESPONSE
DESCRIPTOR.message_types_by_name['FileNameResponse'] = _FILENAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileRequest = _reflection.GeneratedProtocolMessageType('FileRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILEREQUEST,
  '__module__' : 'file_serve_pb2'
  # @@protoc_insertion_point(class_scope:fileserve.FileRequest)
  })
_sym_db.RegisterMessage(FileRequest)

FileListRequest = _reflection.GeneratedProtocolMessageType('FileListRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILELISTREQUEST,
  '__module__' : 'file_serve_pb2'
  # @@protoc_insertion_point(class_scope:fileserve.FileListRequest)
  })
_sym_db.RegisterMessage(FileListRequest)

FileResponse = _reflection.GeneratedProtocolMessageType('FileResponse', (_message.Message,), {
  'DESCRIPTOR' : _FILERESPONSE,
  '__module__' : 'file_serve_pb2'
  # @@protoc_insertion_point(class_scope:fileserve.FileResponse)
  })
_sym_db.RegisterMessage(FileResponse)

FileNameResponse = _reflection.GeneratedProtocolMessageType('FileNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _FILENAMERESPONSE,
  '__module__' : 'file_serve_pb2'
  # @@protoc_insertion_point(class_scope:fileserve.FileNameResponse)
  })
_sym_db.RegisterMessage(FileNameResponse)



_FILESERVICE = _descriptor.ServiceDescriptor(
  name='FileService',
  full_name='fileserve.FileService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=144,
  serialized_end=297,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFile',
    full_name='fileserve.FileService.GetFile',
    index=0,
    containing_service=None,
    input_type=_FILEREQUEST,
    output_type=_FILERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFileList',
    full_name='fileserve.FileService.GetFileList',
    index=1,
    containing_service=None,
    input_type=_FILELISTREQUEST,
    output_type=_FILENAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILESERVICE)

DESCRIPTOR.services_by_name['FileService'] = _FILESERVICE

# @@protoc_insertion_point(module_scope)
